### ISSUE TITLE
Running with camera input or Spout

### ISSUE THREAD

**Issue by brozmical** [keijiro/Pix2Pix#5] opened 2018-09-08 21:58 UTC
Hi Keijiro, excellent work as always. Was wondering how I could implement a game camera as an input via rendertexture for the pix2pix rather than a drawn image? similar to what were doing on your fb videos.

**Comment by keijiro** [comment] 2018-09-09 03:44
I'm trying implementing a post-processing effect with Pix2Pix in the `postprocessing` branch.

https://github.com/keijiro/Pix2Pix/tree/postprocessing

Please check it if you're interested, it's still under heavy development though.

**Comment by keijiro** [comment] 2018-09-09 03:45
I'm closing this issue. Please feel free to reopen for further questions.

**Closed as completed by keijiro** 2018-09-09 03:45 UTC
Labels: question

**Comment by ddutchie** [comment] 2018-09-11 20:29
I am trying this branch with Unity 2018.1.9f2. There are a bunch of Null References and the effect does not show on the main camera only on the scene camera. Any ideas.

`NullReferenceException: Object reference not set to an instance of an object
Pix2Pix.PostProcessing.Pix2PixRenderer.Render (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/Pix2Pix/PostProcessing/Pix2PixEffect.cs:117)`

**Comment by keijiro** [comment] 2018-09-12 02:40
I'm tinkering things in a random fashion. Some parts of them are broken without any fair reason.

**Comment by ddutchie** [comment] 2018-09-12 06:49
It seems the issue is when using both scene view and camera view at the same time. When using them tabbed and only having the camera view it works great.
